package shared_data.communication.client_to_server;

public enum EnumActionResult
{
    REGISTER_SUCCESSFULL("REGISTER_SUCCESSFULL"),
    REGISTER_REFUSED("REGISTER_REFUSED"),

    LOGIN_SUCCESSFULL("LOGIN_SUCCESSFULL"),
    LOGIN_REFUSED("LOGIN_REFUSED"),

    UPLOAD_SONG_SUCCESSFULL("UPLOAD_SONG_SUCCESSFULL"),
    UPLOAD_NOT_SUCCESSFULL("UPLOAD_NOT_SUCCESSFULL"),
    UPLOAD_SONG_ALREADY_EXISTS("UPLOAD_SONG_ALREADY_EXISTS"),

    DOWNLOAD_SONG_SUCCESSFULL("DOWNLOAD_SONG_SUCCESSFULL"),
    DOWNLOAD_SONG_FAILED("DOWNLOAD_SONG_FAILED"),

    EDIT_SONG_NAME_SUCCESSFULL("EDIT_SONG_NAME_SUCCESSFULL"),
    EDIT_SONG_NAME_FAILED("EDIT_SONG_NAME_FAILED"),

    EDIT_SONG_AUTHOR_SUCCESSFULL("EDIT_SONG_AUTHOR_SUCCESSFULL"),
    EDIT_SONG_AUTHOR_FAILED("EDIT_SONG_AUTHOR_FAILED"),

    DELETE_SONG_NAME_SUCCESSFULL("DELETE_SONG_NAME_SUCCESSFULL"),
    DELETE_SONG_NAME_FAILED("DELETE_SONG_NAME_FAILED"),

    CREATE_PLAYLIST_SUCCESSFULL("CREATE_PLAYLIST_SUCCESSFULL"),
    CREATE_PLAYLIST_FAILED("CREATE_PLAYLIST_FAILED"),
    CREATE_PLAYLIST_ALREADY_EXISTS("CREATE_PLAYLIST_ALREADY_EXISTS"),

    EDIT_PLAYLIST_NAME_SUCCESSFULL("EDIT_PLAYLIST_NAME_SUCCESSFULL"),
    EDIT_PLAYLIST_NAME_FAILED("EDIT_PLAYLIST_NAME_FAILED"),

    ADD_SONG_TO_PLAYLIST_SUCCESSFULL("ADD_SONG_TO_PLAYLIST_SUCCESSFULL"),
    ADD_SONG_TO_PLAYLIST_FAILED("ADD_SONG_TO_PLAYLIST_FAILED"),

    REMOVE_SONG_FROM_PLAYLIST_SUCCESSFULL("REMOVE_SONG_FROM_PLAYLIST_SUCCESSFULL"),
    REMOVE_SONG_FROM_PLAYLIST_FAILED("REMOVE_SONG_FROM_PLAYLIST_FAILED"),

    REMOVE_PLAYLIST_SUCCESSFULL("REMOVE_PLAYLIST_SUCCESSFULL"),
    REMOVE_PLAYLIST_FAILED("REMOVE_PLAYLIST_FAILED"),

    DOWNLOAD_PLAYLIST_SUCCESSFULL("DOWNLOAD_PLAYLIST_SUCCESSFULL"),
    DOWNLOAD_PLAYLIST_FAILED("DOWNLOAD_PLAYLIST_FAILED");





    private String value;

    private EnumActionResult(String value)
    {
        this.value = value;
    }

    public String getValue()
    {
        return value;
    }

}